config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'static_pages#home'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :posts
	has_many :comments


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_home_header.html.erb
<nav class="navbar navbar-default">
	<div class="container-fluid">
		 <a class="navbar-brand" href="#">Odinbook</a>

	 <div class="nav navbar-nav navbar-right login">
	   <%= form_for(:user, :url => session_path(:user)) do |f| %>
		  <div class="row">
			 <div class="col-md-4">
			   <%= f.label :email, class: "login-label" %>
			   <%= f.email_field :email, class: "form-control login-input" %>
        </div>

        <div class="col-md-4">
			   <%= f.label :password, class: "login-label" %>
			   <%= f.password_field :password, class: "form-control login-input" %>
        </div>

        <div class="col-md-2 login-btn-pos ">
			   <%= f.submit "Log in", class: "btn btn-primary login-btn" %>
        </div>
		  </div>

      <div class="row">

        <div class="col-md-4">
		      <%= f.check_box :remember_me %>
		      <%= f.label :remember_me, "Keep me logged in", class: "login-label" %>
        </div>
        <div class="col-md-4">
		      <%= link_to "Forgot your password?", new_password_path(resource_name), class: "login-link" %>
        </div>
      </div>

	   <% end %>
		</div>

	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Odinbook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if user_signed_in? %>
	<%= render 'layouts/header' %>
<% else %>
	<%= render 'layouts/home_header' %>
<% end %>

<%= yield %>

</body>
</html>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>